version: '3.8'

name: springboot-ddd

services:
  db:
    container_name: springboot-ddd-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: springboot_ddd
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql  
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    container_name: springboot-ddd-app
    image: eclipse-temurin:17
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATASOURCE_URL: "jdbc:mysql://db:3306/demo"
    tty: true
